export enum ShipmentCost {
	STANDART = 0.39,
	AIRWESTLETTER = 0.39,
	AIRWESTPACKAGE = 0.25,
	AIRWESTOVERSIZED = 10,
	CHICAGOSPRINTLETTER = 0.42,
	CHICAGOSPRINTPACKAGE = 0.2,
	CHICAGOSPRINTOVERSIZED = 0,
	PACIFICPARCELLETTER = 0.51,
	PACIFICPARCELPACKAGE = 0.19,
	PACIFICPARCELOVERSIZED = 0.02
}